### ISSUE TITLE
DrawString not dislpay in image

### ISSUE THREAD

**Issue by czd890** [zkweb-framework/ZKWeb.System.Drawing#11]
```C#
            var img = new Bitmap(500, 500);
            var g = Graphics.FromImage(img);
            g.Clear(Color.Gray);
            g.DrawString("AABB", new Font("Arial", 140), new SolidBrush(Color.Red), new RectangleF(10, 10, 400, 400));
            var sf = g.MeasureString("AABB", new Font("Arial", 140), 500, StringFormat.GenericTypographic);
            Console.WriteLine(sf.Width);
            //windows output 498
            //centos 7 output 0
```
sf.Width
 //windows output 498
//centos 7 output 0
and output image
![image](https://user-images.githubusercontent.com/4011549/32445323-531af17c-c340-11e7-9c18-37ee037546a2.png)

**Comment by 303248153** [comment]
I could't reproduce your problem,
on my environment it outputs 500 and did draw the string on image.
can you try other font name like 'Monospace' or provide more details?

**Comment by czd890** [comment]
copy windowns fronts to /usr/share/fonts/chinese/TrueType/

Solve it, but do not know why.
This situation should throw exception, is not it?
