### ISSUE TITLE
Icon/Bitmap transparency support

### ISSUE THREAD

**Issue by LORDofDOOM** [zkweb-framework/ZKWeb.System.Drawing#3]
I think that's a mono issue (same problem with CoreCompat) but anyway:

It's currently not possible to create a bitmap from a Icon (with transparency e.g. Vista and above Icons) and preserve transparency.

This works with MS .NET framework but not with this library (Background is black, not transparent)

Here is a usage sample: https://github.com/GathSystems/CygwinPortable/blob/master/Source/class/IconFromFile.cs

Thank you

**Comment by 303248153** [comment]
Hello, I can't reproduce your problem.
I just try convert a transparent icon grab from http://findicons.com/icon/22091/abs_icon_transparent?id=22113
with this code
``` csharp
using (var icon = new Icon(@"C:\Users\admin\Downloads\abs_icon_transparent.ico"))
using (var bitmap = icon.ToBitmap()) {
	bitmap.Save(@"C:\Users\admin\Downloads\abs_icon_transparent.png", ImageFormat.Png);
}
```
And it work as excepted.
Maybe the problem is releated to `Icon.FromHandle`.
Can you provide more information?

**Comment by LORDofDOOM** [comment]
Thank you for your response - I've create a Repo to show the problem:

https://github.com/LORDofDOOM/IconExtractorTest

This will extract icon from explorer.exe and save it as fileIconBitmap_NET462.png if compiled with NET 4.6.2 (System.Drawing) and as fileIconBitmap_CoreCLR.png if compiled with CoreCLR (ZKWeb.System.Drawing) - I've added the result pngs into the repo too.

I've also tried to compile with NET 4.6.2 and ZKWeb.System.Drawing - Here the background is also black...

P.S.: The Repo is already for VS2017 with csproj (project.json is no longer used in new dotnet versions) - I hope that's no problem :-)

**Comment by 303248153** [comment]
Thanks for providing the information.
Original System.Drawing will do some additional processing to support the transparent icon after Image.FromHbitmap, I copied that to my fork and it works well as I tested.
Please checkout https://www.nuget.org/packages/ZKWeb.System.Drawing/2.0.1 and see does it work for you too.

**Comment by LORDofDOOM** [comment]
Great - Version 2.0.1 fix the problem :-)

Thank you very much
