### ISSUE TITLE
DotNet Core Debian gdiplus.dll

### ISSUE THREAD

**Issue by dhalucario** [zkweb-framework/ZKWeb.System.Drawing#4]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'DiscordLucarioBotnAPI.Program' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)

**Comment by mclucario** [comment]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'DiscordLucarioBotnAPI.Program' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by 303248153** [comment]
Please see the introduction for ubuntu, did you link libgdiplus.so to gdiplus.dll?

**Comment by dhalucario** [comment]
I just installed it with nuget. nothing else.

**Comment by 303248153** [comment]
Please follow the instruction in README (it didn't write about debian, but you can try ubuntu way first then try centos way)
You need install libgdiplus and create a link named gdiplus.dll to libgdiplus.so

**Comment by 303248153** [comment]
Close since no response in months, if you have any new quesion welcome to reopen this issue.
