### ISSUE TITLE
Can I use this in a .NET Core Console App?

### ISSUE THREAD

**Issue by SuperJMN** [zkweb-framework/ZKWeb.System.Drawing#5]
I want to draw anything on the screen from a .NET Core Application. How does this library help me with that?

Thanks in advance.

**Comment by 303248153** [comment]
Sure you can, but only for processing image data (file), not for drawing directly to screen
Since there no gui library (like winform) for .Net Core yet, I think you may not get what you want

**Comment by 303248153** [comment]
Close since no response in months, if you have any new quesion welcome to reopen this issue.
