### ISSUE TITLE
In Docker: Unable to load DLL 'gdiplus.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by ZhiqiangTao** [zkweb-framework/ZKWeb.System.Drawing#6]
I have made the gdiplus.dll by following your steps.
and build the gdiplus.dll into an docker images. and run a container with this image.
but it still shows "Unable to load DLL 'gdiplus.dll': The specified module could not be found."

**Comment by ZhiqiangTao** [comment]
solution:
FROM microsoft/dotnet:1.0.3-runtime
ENTRYPOINT ["dotnet", "MicBookCustomer.dll"]
WORKDIR /xbookstore/customer/picture
COPY . /xbookstore/customer/picture
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
RUN echo "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list
RUN apt-get update
RUN apt-get install -y libgdiplus
RUN ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll

ENV ASPNETCORE_ENVIRONMENT Development

**Comment by 303248153** [comment]
Thanks, that's a big help
